# Uncomment the next line to define a global platform for your project

platform :ios, '13.1'

target 'iosSim' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosSim
  pod 'app', :path => '/Users/jetbrains/TestProjects/_tasks/MPP/_MMPP/testing/sample-mpp-app/app'

  target 'iosSimTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iosSimUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
